-- Seed data for Prempawee's portfolio knowledge base.
-- Source of truth for LIVE content: scripts/refresh-knowledge-base.mjs.
-- Regenerate after running refresh: npm run kb:refresh + kb:embed.
-- This seed file reflects minimum content for a fresh DB bootstrap —
-- ops may then run refresh-knowledge-base to sync to the current
-- copy in docs/SSS_STATUS.md or via the admin workflow.
-- Embeddings are populated via scripts/generate-embeddings.mjs.

-- BIO
insert into knowledge_base (category, title, content, metadata) values
('bio', 'About Prempawee', 'Prempawee is a One Person Business generalist who ships production AI systems end-to-end from Chiang Mai, Thailand. He graduated in 2026 from the Faculty of Mass Communication at Chiang Mai University, then transitioned into AI-native development with Claude Code as his primary craft. His working principle is simple: reduce weaknesses before adding strengths. Foundations before features, observability before scale. Started as a marketing intern for NWL, a streetwear brand from Bangkok, then grew into managing all digital operations for NWL CLUB. Founded VerdeX Farm, an AI-powered smart greenhouse project. Now builds intelligent LINE OA Chatbot systems, admin dashboards, AI agents, and bilingual systems for Thai businesses. Monthly income goal: 100,000 THB.', '{"education": "Mass Communication, Chiang Mai University, graduated 2026", "location": "Chiang Mai, Thailand", "english_level": "B1", "languages": ["Thai", "English"], "positioning": "One Person Business generalist", "last_updated": "2026-04-26"}'),

('bio', 'Work Philosophy', 'Prempawee''s work philosophy is direct: reduce weaknesses before adding strengths. Foundations first, features second. Production-grade infrastructure ships before scale, observability before growth, maintenance built-in — never retrofitted. Rooted in Stoic discipline: no shortcuts, no silent failures. Adapted from how Prempawee runs his own portfolio site (production-grade security headers, RAG with grounding rules, full E2E test gates, audit log of every silent failure).', '{"last_updated": "2026-04-26"}'),

('bio', 'Generalism over specialism', 'Prempawee operates as a One Person Business generalist, not a single-surface specialist. He works end-to-end across LINE OA chatbots, admin dashboards, AI agents, IoT integrations, RAG systems, full-stack web apps, and bilingual Thai/English systems. The reasoning: a One Person Business with strong foundations can ship across surfaces faster than a multi-vendor team can coordinate — no hand-offs, no integration friction, no scope gaps between vendors.', '{"last_updated": "2026-04-26"}'),

('bio', 'Mass Communication × AI — why the combo matters', 'Prempawee graduated in 2026 from the Faculty of Mass Communication at Chiang Mai University — an unusual background for an AI developer. The combination shows up directly in delivery: Thai prompts in his chatbots sound like natural Thai speech, system prompts handle Thai-English code-switching cleanly, and project documentation is written so that non-technical owners can actually read it. Communication is treated as part of the engineering deliverable, not an afterthought.', '{"last_updated": "2026-04-26"}'),

('bio', 'Personal values', 'Prempawee values reading, writing, and Stoic discipline alongside building. In delivery, this translates to full ownership of the entire stack — design, infrastructure, code, observability, and post-launch maintenance all sit with one person. No hand-offs, no "that''s not my responsibility" moments, no missing accountability between vendors.', '{"last_updated": "2026-04-26"}'),

('bio', 'Skills and Tech Stack', 'Prempawee works with the following technologies: Claude AI (primary LLM for chatbot intelligence), Next.js (React framework for web applications), Supabase (database, authentication, and real-time features), Vercel (deployment on the Edge Network with Analytics and Speed Insights), Cloudflare Workers (serverless edge computing), LINE Messaging API (native LINE integration including Rich Menu, Flex Messages, LIFF apps), Tailwind CSS (responsive design), and various AI development tools including Claude Code and Vibe Coding approach. Development style emphasizes production-grade systems, not demos.', '{"primary_tools": ["Claude AI", "Next.js", "Supabase", "Vercel", "Cloudflare Workers", "LINE Messaging API", "Tailwind CSS"], "dev_tools": ["Claude Code", "Claude MAX 20X"]}');

-- VERDEX FARM PROJECT
insert into knowledge_base (category, title, content, metadata) values
('project', 'VerdeX Farm - Overview', 'VerdeX Farm is Prempawee''s largest project — a complete AI-powered smart greenhouse management system for growing sweet basil using DWC (Deep Water Culture) Hydroponics in Chiang Mai, Thailand. The project consists of 4 major components: a landing page website, a blog platform, an owner command center (admin dashboard), and a LINE OA Bot. The system has been iterated 12 times (Round 12), showing continuous improvement and refinement. The software is fully functional. Hardware sensors are pending assembly.', '{"status": "Software functional, hardware pending", "type": "AI Smart Greenhouse", "crop": "Sweet Basil (DWC Hydroponics)", "location": "Chiang Mai", "iterations": 12}'),

('project', 'VerdeX Farm - Landing Page', 'VerdeX Farm has a public landing page website that introduces the smart farm concept and brand. Built on Cloudflare Workers for fast edge delivery.', '{"url": "https://verdex-web.verdexfarm.workers.dev/", "tech": ["Cloudflare Workers"], "component": "Landing Page"}'),

('project', 'VerdeX Farm - Blog Platform', 'VerdeX Farm includes a blog platform for publishing content about smart farming, AI agriculture, and project updates.', '{"url": "https://verdex-web.verdexfarm.workers.dev/blog/", "tech": ["Cloudflare Workers"], "component": "Blog"}'),

('project', 'VerdeX Farm - Command Center', 'The VerdeX Command Center is an owner-facing admin dashboard (web application) where the farm owner can view real-time status, manage orders, track customers via CRM, and monitor all farm operations. This is the brain of the operation alongside the LINE Bot.', '{"url": "https://verdex-app.verdexfarm.workers.dev/", "tech": ["Cloudflare Workers", "Supabase"], "component": "Owner App / Admin Dashboard"}'),

('project', 'VerdeX Farm - LINE Bot Features', 'The VerdeX Farm LINE Bot is the most feature-rich component. It serves as both an owner console and a customer interface. Owner features include: live sensor data viewing (water temperature, air temperature, humidity), full ordering system (create, confirm, track, deliver, cancel orders with automatic revenue recording), stock management with 3 states (ready, low, out of stock), farm batch logging and harvest recording (e.g., harvested 3 kg), expense tracking, VIP customer system with customer lookup and top customer ranking, automated morning reports sent daily at 07:00, and AI Weekly Pulse reports powered by Claude Opus that analyze environmental conditions and business metrics. Customer features include ordering sweet basil directly through LINE conversation. The bot uses Rich Menu and Flex Messages for a professional interface.', '{"tech": ["LINE Messaging API", "Claude AI", "Supabase", "Rich Menu", "Flex Messages"], "component": "LINE Bot", "iteration": "Round 12", "ai_model": "Claude Opus for weekly analysis"}'),

('project', 'VerdeX Farm - Weekly Pulse Report', 'The VerdeX Weekly Pulse is an automated AI-generated report that analyzes farm performance. It includes environmental conditions (water temperature avg, air temperature avg, humidity avg with percentage in optimal range), business data (revenue in THB, number of orders, number of shops, harvest weight in kg), and an AI Insight section where Claude Opus analyzes sensor stability scores, identifies anomalies, and provides recommendations. Example report showed: Sensor Stability Score 44/100, water temp 22.9C (33% in range), air temp 27.3C (67% in range), humidity 60.4% (33% in range), revenue 360 THB, 3 orders, 5.5 kg harvested.', '{"component": "AI Weekly Report", "ai_model": "Claude Opus"}');

-- NWL CLUB PROJECT
insert into knowledge_base (category, title, content, metadata) values
('project', 'NWL CLUB - Overview', 'NWL CLUB is a project Prempawee built for NWL, a streetwear brand from Bangkok. Prempawee interned at NWL as a marketing representative and now manages all digital operations including the NWL CLUB page. The project consists of 2 web applications: a Work Tracker for employee management and a Club Website for the brand''s customer community. Both are running on production and can be upgraded further.', '{"brand": "NWL", "type": "Streetwear brand from Bangkok", "role": "Admin / Developer"}'),

('project', 'NWL CLUB - Work Tracker', 'The NWL Work Tracker is an employee management web application with check-in and check-out functionality and work tracking features. Built with Next.js, Supabase, and Tailwind CSS, deployed on Vercel. Running on production.', '{"url": "https://nwl-work-tracker.vercel.app/", "tech": ["Next.js", "Supabase", "Tailwind CSS", "Vercel"], "component": "Work Tracker", "status": "Production"}'),

('project', 'NWL CLUB - Community Website', 'The NWL CLUB Community Website serves as the main website for the NWL clothing brand''s customer community. Built with Next.js, Supabase, and Tailwind CSS, deployed on Vercel. Running on production and can be upgraded.', '{"url": "https://nwl-club-website.vercel.app/", "tech": ["Next.js", "Supabase", "Tailwind CSS", "Vercel"], "component": "Community Website", "status": "Production"}');

-- PORTFOLIO WEBSITE PROJECT
insert into knowledge_base (category, title, content, metadata) values
('project', 'Portfolio Website - This Site', 'This portfolio website is itself a project built by Prempawee. It is an AI-powered chatbot that serves as the portfolio. Instead of a traditional portfolio with static pages, visitors interact with an AI that dynamically presents information, shows pricing cards, case studies, tech stack details, and contact information through the conversation. The medium is the message, proving that Prempawee can build AI chat systems. Built with Next.js, Vercel AI SDK, Claude API (Sonnet), and deployed on Vercel. Features Matrix-inspired design aesthetic with black background, monospace typography, and dot grid pattern.', '{"tech": ["Next.js", "Vercel AI SDK", "Claude Sonnet", "Tailwind CSS", "Vercel", "Supabase pgvector for RAG"], "design": "Matrix-inspired, black/white, monospace", "status": "In development"}');

-- SERVICE PACKAGES
insert into knowledge_base (category, title, content, metadata) values
('package', 'LINE OA Starter Package', 'The LINE OA Starter package costs 5,000 THB with 5-day delivery and 2 revisions. It is suitable for businesses that want to start with professional LINE OA automation without high investment. What the client gets: LINE OA connected to Messaging API, Rich Menu design and installation (6 buttons), Greeting Message for new followers, auto-reply for keywords (up to 10 keywords), 1 Flex Message template, testing on staging environment before production deploy, deployed to production ready to use, basic usage guide, 7-day bug warranty after delivery, and chat support after delivery.', '{"price": 5000, "currency": "THB", "delivery_days": 5, "revisions": 2, "tier": "starter"}'),

('package', 'Smart Chatbot Pro Package', 'The Smart Chatbot Pro package costs 18,000 THB with 14-day delivery and 3 revisions. It is suitable for businesses with high chat volume that need a chatbot powered by Claude AI that understands Thai naturally, not just keyword matching. Includes everything in the Starter package PLUS: Claude AI chatbot that understands natural Thai language, conversation flow up to 25 paths, 3 Flex Message templates (catalog, booking, order), Rich Menu switching based on user type, connection to Google Sheets or webhook (1 system), customer data stored in Supabase database, basic CRM dashboard (LIFF app), complete source code and documentation, 30-minute video training session, and 14-day support after delivery.', '{"price": 18000, "currency": "THB", "delivery_days": 14, "revisions": 3, "tier": "pro"}'),

('package', 'Enterprise AI Package', 'The Enterprise AI package costs 45,000 THB with 30-day delivery and unlimited revisions. It is a complete intelligent LINE OA system suitable for businesses that want to invest in a long-term system. Includes everything in the Pro package PLUS: Claude AI with advanced conversation memory, LIFF app for booking or ordering (web app inside LINE), PromptPay QR or automatic payment slip verification, booking and appointment system with push notification reminders, loyalty points accumulation and membership tier system, admin dashboard for the business owner, broadcast campaign support with audience segmentation, 60-minute live training session plus video recording, complete documentation, and 30-day support after delivery.', '{"price": 45000, "currency": "THB", "delivery_days": 30, "revisions": "unlimited", "tier": "enterprise"}');

-- FAQs
insert into knowledge_base (category, title, content, metadata) values
('faq', 'What makes Prempawee different from other chatbot developers?', 'Four things set Prempawee apart from typical AI freelancers. First, foundations-first delivery — production-grade infrastructure, observability, and security ship before features. Maintenance is built-in, not retrofitted. Second, generalist breadth — as a One Person Business, he ships end-to-end across web apps, admin dashboards, IoT integrations, AI agents, and chatbots. No vendor coordination overhead, no integration gaps. Third, bilingual EN/TH delivery — Thai prompts that sound natural to Thai users, English documentation for international stakeholders, clean code-switching in production systems. Fourth, communication training — a Mass Communication background means project documentation, prompt design, and client conversations are treated as part of the engineering deliverable. LINE OA chatbots are one example among several surfaces he ships — the published packages are named around them because that''s the most common request from Thai SMEs.', '{"last_updated": "2026-04-26"}'),

('faq', 'Are you only good at LINE OA chatbots?', 'No. LINE OA chatbots are one of several surfaces Prempawee ships across. He delivers end-to-end on web apps (Next.js, Cloudflare Workers), admin dashboards (Supabase, real-time data), IoT integrations (sensors, MQTT), AI agents (Claude tool-use, RAG), and bilingual Thai/English systems. The published packages are named around chatbots because that''s the most common request from Thai SMEs — but custom scopes are quoted on a per-project basis.', '{"last_updated": "2026-04-26"}'),

('faq', 'How many projects has Prempawee completed?', 'Prempawee has built 3 major projects consisting of 6 web properties and 1 LINE bot: VerdeX Farm (landing page + blog + command center app + LINE bot), NWL CLUB (work tracker + community website), and this AI-powered portfolio website. Each project demonstrates different capabilities, from AI chatbot systems to employee management to community platforms.', '{}'),

('faq', 'What is the work process?', 'Prempawee follows a 4-step professional work process: Step 1 is consultation to understand the client needs via a requirement form covering business info, target customers, frequently asked questions, and desired conversation flow. Step 2 is system design, presenting conversation flow diagrams and Rich Menu wireframes for approval before development begins. Step 3 is development and testing on a staging environment where the client can interact with the chatbot before production deployment. Step 4 is deployment and handoff with documentation and video tutorial. The client needs to provide: admin access to LINE OA and LINE Developers Console, product/service list with prices and images, at least 20 FAQ items, tone of voice guidelines, and clear feedback at each phase.', '{}'),

('faq', 'Can I start with a small package and upgrade later?', 'Yes, absolutely. The Starter package at 5,000 THB is designed for businesses that want to test the quality before committing to a larger investment. You can start with the Starter package and upgrade to Smart Chatbot Pro or Enterprise AI later. Prempawee will discuss what makes sense for your specific business needs during a free consultation.', '{}'),

('faq', 'What about ongoing support and maintenance?', 'Each package includes support after delivery: Starter has 7-day bug warranty plus chat support, Pro has 14-day support with video training, and Enterprise has 30-day support with live training. For ongoing maintenance beyond these periods, Prempawee can discuss a maintenance agreement separately. All systems are built with clean code and documentation so the client or another developer can maintain them if needed.', '{}'),

('faq', 'Contact information', 'You can reach Prempawee through: Personal LINE (Prempawee), Email (prempaweet20@gmail.com), LinkedIn (linkedin.com/in/prempaweedevth), or through Fastwork for ordering packages directly. Free consultation available. Typically responds within 2-4 hours during working hours. Custom quotes available for projects that do not fit the standard packages.', '{"email": "prempaweet20@gmail.com", "linkedin": "linkedin.com/in/prempaweedevth"}'),

('faq', 'What infrastructure powers this portfolio?', 'The portfolio chat API is a Next.js 16 App Router route on Vercel''s serverless functions. Incoming requests are rate-limited by IP using Upstash Redis with atomic fixed-window counters (3 sessions per hour in production, bypassed in development). Request bodies pass through Zod schema validation. The system prompt is composed from a base set of rules plus the Supabase knowledge_base RAG content (fetched and cached for 5 minutes per instance). Claude Sonnet streams responses through the AI SDK v6 with ephemeral prompt caching for lower cost. Tool calls map to rich UI cards on the client. Conversations and analytics events are logged to Supabase asynchronously with structured errors. CSP, HSTS, X-Frame-Options, and Permissions-Policy headers are set at the CDN edge. Error boundaries at both segment and global level catch any render failures, and a static fallback page (/fallback) serves the same breadth-first content without the AI when needed.', '{"last_updated": "2026-04-17", "components": ["Vercel Edge Network", "Upstash Redis", "Supabase Postgres", "Anthropic Claude Sonnet", "AI SDK v6", "Next.js middleware", "error.tsx / global-error.tsx"]}'),

('faq', 'What about NDAs and IP ownership?', 'Prempawee will sign client-provided NDAs after a 15-minute discovery call. Default IP terms: the client owns all deliverables (source code, designs, documentation) on final payment. Prempawee retains the right to reference the work in his portfolio (project name, technology stack, public-facing screenshots), with any sensitive numbers, client identities, or business-confidential details redacted. If the client requires full confidentiality, this is negotiable but typically affects pricing because it removes the portfolio reference value.', '{}'),

('faq', 'What are the payment terms?', 'Standard payment terms across all three packages: 50% upfront at kickoff, 50% on delivery. Preferred method is PromptPay (THB) for Thai clients; bank transfer is also accepted. Invoices are issued at kickoff and at delivery. International clients can pay via bank transfer in THB equivalent. The 50% upfront covers research, design, and initial build; the 50% on delivery is paid after the staging environment passes client acceptance and before production deploy.', '{}'),

('faq', 'What about maintenance after the warranty period?', 'Each package includes a built-in warranty period: Starter 7 days, Pro 14 days, Enterprise 30 days. After the warranty period ends, ongoing maintenance is available two ways. Ad-hoc rate: 800 THB per hour, billed in 30-minute increments. Monthly retainer: 8,000 THB per month, includes 12 hours of work, with same-business-day response for any reported issue. Hours beyond the retainer are 700 THB per hour. Retainer can be paused or cancelled with 30 days notice. The retainer is the right choice for clients running production systems who want a predictable response SLA; ad-hoc is the right choice for occasional fixes.', '{}'),

('faq', 'Does Prempawee accept equity or revenue share instead of cash?', 'At this stage of the business, Prempawee works on cash-only terms. Equity, revenue share, or other non-cash compensation may be considered case-by-case for unique opportunities — typically projects valued at 200,000 THB equivalent or higher with a clear product-market fit signal. For early-stage startups without funding, the more practical path is usually a smaller-scope cash-paid Starter or Pro package to validate the build before committing to a larger build with non-cash terms.', '{}'),

('faq', 'What are the working hours and meeting availability?', 'Prempawee is based in Chiang Mai and works in Indochina Time (UTC+7). Standard working hours are weekdays, with response time of 2 to 4 hours during working hours for chat, email, and LINE messages. Synchronous video meetings are available for the free 15-minute consultation, kickoff, and major milestone reviews; otherwise the working style is async-first to maximize build time. International clients in EU or US time zones: meetings can be scheduled outside Bangkok working hours by mutual agreement, but day-to-day async communication remains the default.', '{}'),

('faq', 'What does the client receive on delivery day?', 'On delivery day, every package includes the following 8 deliverables: (1) source code repository access on GitHub or as a zipped archive, (2) deployment credentials including hosting login and database access, (3) ENV variable documentation listing every required key with rotation guidance, (4) video tutorial in Thai walking through admin operations and common tasks, (5) written runbook in Markdown format with bilingual sections, (6) signed warranty terms document specifying the warranty window for the purchased package, (7) ongoing support channel via LINE chat or email, and (8) a system architecture diagram showing components and data flow. The Pro and Enterprise packages additionally include 30-minute and 60-minute live training sessions respectively.', '{}'),

('faq', 'What language are the deliverables and documentation in?', 'Source code comments are in English, since the technical stack (TypeScript, React, Supabase, Anthropic SDK) and likely future maintainers expect English. Written documentation is in English with a Thai language summary at the top of each document, so a non-English-reading owner can understand the system at a glance. Video tutorials are recorded in Thai, since the daily operator is most often a Thai-speaking business owner or staff member. The chatbot itself, if part of the project, runs bilingually EN and TH from day one. If the client prefers Thai-only or English-only deliverables, this is configurable at kickoff.', '{}'),

('faq', 'When does the timeline start, and what causes delays?', 'Quoted timelines (Starter 5 days, Pro 14 days, Enterprise 30 days) start from the approved-specification date, not the date of inquiry. The approved-specification milestone happens after the free 15-minute consultation, the requirement form is completed, and Prempawee delivers a flow diagram and Rich Menu wireframes for client approval. Common delay drivers, all flagged at kickoff: LINE OA admin access not granted from the LINE Developers Console adds typically 2 to 3 days, content and copy not provided by client adds 3 to 5 days, mid-project scope changes vary in impact and are quoted as a separate change order. Prempawee will surface delay risk in writing within 24 hours of the cause appearing, so neither side discovers a missed date in the final week.', '{}');
