-- Seed data for Prempawee's portfolio knowledge base.
-- Source of truth for LIVE content: scripts/refresh-knowledge-base.mjs.
-- Regenerate after running refresh: npm run kb:refresh + kb:embed.
-- This seed file reflects minimum content for a fresh DB bootstrap —
-- ops may then run refresh-knowledge-base to sync to the current
-- copy in docs/SSS_STATUS.md or via the admin workflow.
-- Embeddings are populated via scripts/generate-embeddings.mjs.

-- BIO
insert into knowledge_base (category, title, content, metadata) values
('bio', 'About Prempawee', 'Prempawee is an AI developer and One Person Business based in Chiang Mai, Thailand. Graduated from the Faculty of Mass Communication at Chiang Mai University. Started as a marketing intern for NWL, a streetwear brand from Bangkok, and grew into managing all digital operations for NWL CLUB. Founded VerdeX Farm, an AI-powered smart greenhouse project. Now builds intelligent LINE OA Chatbot systems for Thai businesses. Believes AI is essential for the future and is committed to using AI skills to generate income and build real products. Monthly income goal: 100,000 THB.', '{"education": "Mass Communication, Chiang Mai University", "location": "Chiang Mai, Thailand", "english_level": "B1", "languages": ["Thai", "English"]}'),

('bio', 'Skills and Tech Stack', 'Prempawee works with the following technologies: Claude AI (primary LLM for chatbot intelligence), Next.js (React framework for web applications), Supabase (database, authentication, and real-time features), Vercel (deployment with 99.99% uptime), Cloudflare Workers (serverless edge computing), LINE Messaging API (native LINE integration including Rich Menu, Flex Messages, LIFF apps), Tailwind CSS (responsive design), and various AI development tools including Claude Code and Vibe Coding approach. Development style emphasizes production-grade systems, not demos.', '{"primary_tools": ["Claude AI", "Next.js", "Supabase", "Vercel", "Cloudflare Workers", "LINE Messaging API", "Tailwind CSS"], "dev_tools": ["Claude Code", "Claude MAX 20X"]}');

-- VERDEX FARM PROJECT
insert into knowledge_base (category, title, content, metadata) values
('project', 'VerdeX Farm - Overview', 'VerdeX Farm is Prempawee''s largest project — a complete AI-powered smart greenhouse management system for growing sweet basil using DWC (Deep Water Culture) Hydroponics in Chiang Mai, Thailand. The project consists of 4 major components: a landing page website, a blog platform, an owner command center (admin dashboard), and a LINE OA Bot. The system has been iterated 12 times (Round 12), showing continuous improvement and refinement. The software is fully functional. Hardware sensors are pending assembly.', '{"status": "Software functional, hardware pending", "type": "AI Smart Greenhouse", "crop": "Sweet Basil (DWC Hydroponics)", "location": "Chiang Mai", "iterations": 12}'),

('project', 'VerdeX Farm - Landing Page', 'VerdeX Farm has a public landing page website that introduces the smart farm concept and brand. Built on Cloudflare Workers for fast edge delivery.', '{"url": "https://verdex-web.verdexfarm.workers.dev/", "tech": ["Cloudflare Workers"], "component": "Landing Page"}'),

('project', 'VerdeX Farm - Blog Platform', 'VerdeX Farm includes a blog platform for publishing content about smart farming, AI agriculture, and project updates.', '{"url": "https://verdex-web.verdexfarm.workers.dev/blog/", "tech": ["Cloudflare Workers"], "component": "Blog"}'),

('project', 'VerdeX Farm - Command Center', 'The VerdeX Command Center is an owner-facing admin dashboard (web application) where the farm owner can view real-time status, manage orders, track customers via CRM, and monitor all farm operations. This is the brain of the operation alongside the LINE Bot.', '{"url": "https://verdex-app.verdexfarm.workers.dev/", "tech": ["Cloudflare Workers", "Supabase"], "component": "Owner App / Admin Dashboard"}'),

('project', 'VerdeX Farm - LINE Bot Features', 'The VerdeX Farm LINE Bot is the most feature-rich component. It serves as both an owner console and a customer interface. Owner features include: live sensor data viewing (water temperature, air temperature, humidity), full ordering system (create, confirm, track, deliver, cancel orders with automatic revenue recording), stock management with 3 states (ready, low, out of stock), farm batch logging and harvest recording (e.g., harvested 3 kg), expense tracking, VIP customer system with customer lookup and top customer ranking, automated morning reports sent daily at 07:00, and AI Weekly Pulse reports powered by Claude Opus that analyze environmental conditions and business metrics. Customer features include ordering sweet basil directly through LINE conversation. The bot uses Rich Menu and Flex Messages for a professional interface.', '{"tech": ["LINE Messaging API", "Claude AI", "Supabase", "Rich Menu", "Flex Messages"], "component": "LINE Bot", "iteration": "Round 12", "ai_model": "Claude Opus for weekly analysis"}'),

('project', 'VerdeX Farm - Weekly Pulse Report', 'The VerdeX Weekly Pulse is an automated AI-generated report that analyzes farm performance. It includes environmental conditions (water temperature avg, air temperature avg, humidity avg with percentage in optimal range), business data (revenue in THB, number of orders, number of shops, harvest weight in kg), and an AI Insight section where Claude Opus analyzes sensor stability scores, identifies anomalies, and provides recommendations. Example report showed: Sensor Stability Score 44/100, water temp 22.9C (33% in range), air temp 27.3C (67% in range), humidity 60.4% (33% in range), revenue 360 THB, 3 orders, 5.5 kg harvested.', '{"component": "AI Weekly Report", "ai_model": "Claude Opus"}');

-- NWL CLUB PROJECT
insert into knowledge_base (category, title, content, metadata) values
('project', 'NWL CLUB - Overview', 'NWL CLUB is a project Prempawee built for NWL, a streetwear brand from Bangkok. Prempawee interned at NWL as a marketing representative and now manages all digital operations including the NWL CLUB page. The project consists of 2 web applications: a Work Tracker for employee management and a Club Website for the brand''s customer community. Both are running on production and can be upgraded further.', '{"brand": "NWL", "type": "Streetwear brand from Bangkok", "role": "Admin / Developer"}'),

('project', 'NWL CLUB - Work Tracker', 'The NWL Work Tracker is an employee management web application with check-in and check-out functionality and work tracking features. Built with Next.js, Supabase, and Tailwind CSS, deployed on Vercel. Running on production.', '{"url": "https://nwl-work-tracker.vercel.app/", "tech": ["Next.js", "Supabase", "Tailwind CSS", "Vercel"], "component": "Work Tracker", "status": "Production"}'),

('project', 'NWL CLUB - Community Website', 'The NWL CLUB Community Website serves as the main website for the NWL clothing brand''s customer community. Built with Next.js, Supabase, and Tailwind CSS, deployed on Vercel. Running on production and can be upgraded.', '{"url": "https://nwl-club-website.vercel.app/", "tech": ["Next.js", "Supabase", "Tailwind CSS", "Vercel"], "component": "Community Website", "status": "Production"}');

-- PORTFOLIO WEBSITE PROJECT
insert into knowledge_base (category, title, content, metadata) values
('project', 'Portfolio Website - This Site', 'This portfolio website is itself a project built by Prempawee. It is an AI-powered chatbot that serves as the portfolio. Instead of a traditional portfolio with static pages, visitors interact with an AI that dynamically presents information, shows pricing cards, case studies, tech stack details, and contact information through the conversation. The medium is the message, proving that Prempawee can build AI chat systems. Built with Next.js, Vercel AI SDK, Claude API (Sonnet), and deployed on Vercel. Features Matrix-inspired design aesthetic with black background, monospace typography, and dot grid pattern.', '{"tech": ["Next.js", "Vercel AI SDK", "Claude Sonnet", "Tailwind CSS", "Vercel", "Supabase pgvector for RAG"], "design": "Matrix-inspired, black/white, monospace", "status": "In development"}');

-- SERVICE PACKAGES
insert into knowledge_base (category, title, content, metadata) values
('package', 'LINE OA Starter Package', 'The LINE OA Starter package costs 5,000 THB with 5-day delivery and 2 revisions. It is suitable for businesses that want to start with professional LINE OA automation without high investment. What the client gets: LINE OA connected to Messaging API, Rich Menu design and installation (6 buttons), Greeting Message for new followers, auto-reply for keywords (up to 10 keywords), 1 Flex Message template, testing on staging environment before production deploy, deployed to production ready to use, basic usage guide, 7-day bug warranty after delivery, and chat support after delivery.', '{"price": 5000, "currency": "THB", "delivery_days": 5, "revisions": 2, "tier": "starter"}'),

('package', 'Smart Chatbot Pro Package', 'The Smart Chatbot Pro package costs 18,000 THB with 14-day delivery and 3 revisions. It is suitable for businesses with high chat volume that need a chatbot powered by Claude AI that understands Thai naturally, not just keyword matching. Includes everything in the Starter package PLUS: Claude AI chatbot that understands natural Thai language, conversation flow up to 25 paths, 3 Flex Message templates (catalog, booking, order), Rich Menu switching based on user type, connection to Google Sheets or webhook (1 system), customer data stored in Supabase database, basic CRM dashboard (LIFF app), complete source code and documentation, 30-minute video training session, and 14-day support after delivery.', '{"price": 18000, "currency": "THB", "delivery_days": 14, "revisions": 3, "tier": "pro"}'),

('package', 'Enterprise AI Package', 'The Enterprise AI package costs 45,000 THB with 30-day delivery and unlimited revisions. It is a complete intelligent LINE OA system suitable for businesses that want to invest in a long-term system. Includes everything in the Pro package PLUS: Claude AI with advanced conversation memory, LIFF app for booking or ordering (web app inside LINE), PromptPay QR or automatic payment slip verification, booking and appointment system with push notification reminders, loyalty points accumulation and membership tier system, admin dashboard for the business owner, broadcast campaign support with audience segmentation, 60-minute live training session plus video recording, complete documentation, and 30-day support after delivery.', '{"price": 45000, "currency": "THB", "delivery_days": 30, "revisions": "unlimited", "tier": "enterprise"}');

-- FAQs
insert into knowledge_base (category, title, content, metadata) values
('faq', 'What makes Prempawee different from other chatbot developers?', 'Prempawee''s chatbots use Claude AI which understands natural Thai language, not just keyword matching like most chatbot services (ZWIZ.AI, Botnoi, etc.). The systems are built on production-grade infrastructure (Vercel with 99.99% uptime, Supabase database) that can scale with the business. Prempawee also has a Mass Communication background which means understanding both the technology AND the marketing/communication side of chatbot design. The VerdeX Farm project demonstrates the depth of capability with 12 iterations, showing commitment to quality and continuous improvement.', '{}'),

('faq', 'How many projects has Prempawee completed?', 'Prempawee has built 3 major projects consisting of 6 web properties and 1 LINE bot: VerdeX Farm (landing page + blog + command center app + LINE bot), NWL CLUB (work tracker + community website), and this AI-powered portfolio website. Each project demonstrates different capabilities, from AI chatbot systems to employee management to community platforms.', '{}'),

('faq', 'What is the work process?', 'Prempawee follows a 4-step professional work process: Step 1 is consultation to understand the client needs via a requirement form covering business info, target customers, frequently asked questions, and desired conversation flow. Step 2 is system design, presenting conversation flow diagrams and Rich Menu wireframes for approval before development begins. Step 3 is development and testing on a staging environment where the client can interact with the chatbot before production deployment. Step 4 is deployment and handoff with documentation and video tutorial. The client needs to provide: admin access to LINE OA and LINE Developers Console, product/service list with prices and images, at least 20 FAQ items, tone of voice guidelines, and clear feedback at each phase.', '{}'),

('faq', 'Can I start with a small package and upgrade later?', 'Yes, absolutely. The Starter package at 5,000 THB is designed for businesses that want to test the quality before committing to a larger investment. You can start with the Starter package and upgrade to Smart Chatbot Pro or Enterprise AI later. Prempawee will discuss what makes sense for your specific business needs during a free consultation.', '{}'),

('faq', 'What about ongoing support and maintenance?', 'Each package includes support after delivery: Starter has 7-day bug warranty plus chat support, Pro has 14-day support with video training, and Enterprise has 30-day support with live training. For ongoing maintenance beyond these periods, Prempawee can discuss a maintenance agreement separately. All systems are built with clean code and documentation so the client or another developer can maintain them if needed.', '{}'),

('faq', 'Contact information', 'You can reach Prempawee through: Personal LINE (Prempawee), Email (prempaweet20@gmail.com), LinkedIn (linkedin.com/in/prempawee), or through Fastwork for ordering packages directly. Free consultation available. Typically responds within 2-4 hours during working hours. Custom quotes available for projects that do not fit the standard packages.', '{"email": "prempaweet20@gmail.com", "linkedin": "linkedin.com/in/prempawee"}');
