// Preview-route bilingual strings. Every numeric / proper-noun claim must
// trace verbatim to portfolio-data.ts, supabase-seed.sql, or chat/route.ts.
// Same GROUNDING RULE as the chatbot — applies to marketing copy too.

export type Lang = "en" | "th";

export const STR = {
  en: {
    nav_work: "WORK",
    nav_pricing: "PRICING",
    nav_cases: "CASES",
    nav_contact: "CONTACT",
    nav_open_menu: "Open menu",
    nav_close_menu: "Close menu",
    nav_skip: "Skip to content",
    suggest_pricing: "How much for a chatbot?",
    headline: "talk to my portfolio",
    subhead:
      "the AI knows every project, price, and timeline. ask anything.",
    hero_kicker:
      "PORTFOLIO_AI :: v.2026.04 :: sonnet · edge · RAG-grounded",
    hero_try_terminal: "↘ TRY THE TERMINAL ON THE RIGHT",
    hero_online: "ONLINE",
    stat_live_value: "8+",
    stat_live_label: "live projects",
    stat_ttfb_value: "< 400ms",
    stat_ttfb_label: "TTFB · edge",
    stat_hallu_value: "0",
    stat_hallu_label: "hallucinations",
    statusLabel: "STATUS · ONLINE",
    scroll: "SCROLL",
    locale: "v.2026.04 · CHIANG MAI · TH",
    proof_kicker: "[02] SHIPPED",
    proof_help: "EVERY URL IS LIVE · CLICK TO VISIT",
    proof_read: "READ CASE",
    featured_kicker: "[03] FEATURED CASE",
    featured_meta: "VERDEX FARM · 2026",
    featured_headline_l1: "verdex farm,",
    featured_headline_l2: "start to ship.",
    featured_body:
      "Smart greenhouse pilot for Thai citrus farmers. Landing page, blog, owner command center web app, and a LINE bot delivering daily 07:00 Morning Reports plus weekly Pulse Reports. Bilingual EN/TH end to end. Built solo on Next.js, Supabase, Vercel, and Claude — the full case study covers requirements, architecture, screenshots, and tradeoffs.",
    featured_cta: "READ THE FULL CASE STUDY →",
    build_kicker: "[01] WHAT I BUILD",
    build: [
      {
        k: "CHATBOTS",
        points: [
          "RAG over Supabase + pgvector",
          "Tool-use cards inline in chat",
          "Edge runtime, bilingual EN/TH",
        ],
      },
      {
        k: "DASHBOARDS",
        points: [
          "Owner Command Center for VerdeX Farm",
          "Realtime sensor + business data",
          "RLS on every table, per-user gating",
        ],
      },
      {
        k: "LINE OA",
        points: [
          "Rich Menu + Flex Messages + LIFF",
          "Claude weekly Pulse Reports",
          "Daily 07:00 Morning Reports",
        ],
      },
    ],
    process_kicker: "[02] PROCESS",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "Free 15-minute consultation. Requirement form covers business, customers, FAQs, desired flow. We map the constraint and the ship date.",
      },
      {
        n: "02",
        t: "DESIGN",
        d: "Conversation flow diagrams + Rich Menu wireframes. Approved in writing before any code is written. No scope drift, no surprises.",
      },
      {
        n: "03",
        t: "BUILD & TEST",
        d: "Working slice on a staging URL within the package timeline. Real data, real model, real LINE OA — you click the same buttons your customers will.",
      },
      {
        n: "04",
        t: "DEPLOY & HANDOFF",
        d: "Production deploy. Full source code + ENV docs + Thai video tutorial + warranty terms. The keys are yours from day one.",
      },
    ],
    chat_kicker: "[03] TALK TO ME",
    chat_title: "ASK THE PORTFOLIO",
    chat_help: "try a suggestion ↓",
    pdpa: "This chat may store messages to improve service. No data is shared with third parties.",
    pdpa_accept: "I UNDERSTAND",
    placeholder: "What do you need built? Describe your project...",
    send: "SEND",
    cap: "session :: 20 messages max",
    cap_reached: "Limit reached — contact via LINE or email",
    suggest: [
      "Walk me through the VerdeX Farm case.",
      "How do you avoid hallucinations?",
      "How much for a chatbot?",
      "Are you free in May?",
    ],
    contact_label: "CONTACT",
    contact: [
      { k: "LINE", href: "https://line.me/ti/p/EeqOwz9udS" },
      { k: "EMAIL", href: "mailto:prempaweet20@gmail.com" },
      { k: "LINKEDIN", href: "https://www.linkedin.com/in/prempaweedevth" },
      { k: "GITHUB", href: "https://github.com/premkung87-star" },
    ],
    footer_links: [
      { k: "VERDEX", href: "/case-studies/verdex" },
      { k: "PORTFOLIO META", href: "/case-studies/this-portfolio" },
      { k: "FALLBACK", href: "/fallback" },
      { k: "STATUS", href: "/status" },
    ],
    philosophy_kicker: "[02c] PHILOSOPHY",
    philosophy_quote:
      "Build the strongest foundation possible, minimize weaknesses, before increasing strengths.",
    philosophy_attribution: "Prempawee · One Person Business",
    feedback_link: "GIVE FEEDBACK",
    feedback_kicker: "[FEEDBACK]",
    feedback_type_label: "TYPE",
    feedback_types: {
      bug: "BUG",
      suggestion: "SUGGESTION",
      thanks: "THANKS",
      other: "OTHER",
    },
    feedback_body_label: "MESSAGE",
    feedback_body_placeholder: "What's on your mind?",
    feedback_email_label: "EMAIL",
    feedback_email_help: "(optional — if you'd like a reply)",
    feedback_email_placeholder: "you@example.com",
    feedback_consent:
      "By submitting, you consent to storing your feedback and email if provided. No data shared with third parties.",
    feedback_submit: "SUBMIT",
    feedback_submitting: "SENDING...",
    feedback_thanks: "Thanks. Your feedback is logged.",
    feedback_close: "CLOSE",
    feedback_error:
      "Couldn't send. Please try again or email directly.",
    feedback_error_validation: "Please fill out the form correctly.",
    feedback_error_rate_limited:
      "Too many submissions. Try again in an hour.",
    welcome:
      "Welcome. I'm Prempawee's portfolio AI. He's a Solo AI Developer in Chiang Mai shipping production systems for Thai businesses — LINE chatbots, admin dashboards, IoT, AI agents. All Claude-powered, all deployed, all live.",
  },
  th: {
    nav_work: "ผลงาน",
    nav_pricing: "ราคา",
    nav_cases: "เคสศึกษา",
    nav_contact: "ติดต่อ",
    nav_open_menu: "เปิดเมนู",
    nav_close_menu: "ปิดเมนู",
    nav_skip: "ข้ามไปที่เนื้อหา",
    suggest_pricing: "chatbot ราคาเท่าไหร่?",
    headline: "คุยกับ portfolio ผม",
    subhead: "AI รู้ทุกโปรเจกต์ ราคา และ timeline. ถามอะไรก็ได้.",
    hero_kicker: "PORTFOLIO_AI :: v.2026.04 :: sonnet · edge · RAG",
    hero_try_terminal: "↘ ลองถามดูในกล่องด้านขวา",
    hero_online: "ONLINE",
    stat_live_value: "8+",
    stat_live_label: "โปรเจกต์ที่ live",
    stat_ttfb_value: "< 400ms",
    stat_ttfb_label: "TTFB · edge",
    stat_hallu_value: "0",
    stat_hallu_label: "hallucinations",
    statusLabel: "STATUS · ONLINE",
    scroll: "เลื่อน",
    locale: "v.2026.04 · เชียงใหม่ · TH",
    proof_kicker: "[02] งานที่ส่งมอบแล้ว",
    proof_help: "ทุก URL ใช้งานได้จริง · กดเพื่อเปิด",
    proof_read: "ดูรายละเอียด",
    featured_kicker: "[03] เคสที่เลือกมา",
    featured_meta: "VERDEX FARM · 2026",
    featured_headline_l1: "verdex farm,",
    featured_headline_l2: "ตั้งแต่เริ่มถึงส่งมอบ.",
    featured_body:
      "Smart greenhouse pilot สำหรับชาวสวนส้มไทย. Landing page, blog, owner command center web app, และ LINE bot ที่ส่ง Morning Report 07:00 ทุกวัน พร้อม Pulse Report รายสัปดาห์. EN/TH สองภาษาเต็มทั้งระบบ. สร้างคนเดียวบน Next.js, Supabase, Vercel, และ Claude — case study เต็มมีทั้ง requirement, architecture, screenshot, และ tradeoff.",
    featured_cta: "อ่านเคสแบบเต็ม →",
    build_kicker: "[01] ผมสร้างอะไร",
    build: [
      {
        k: "CHATBOTS",
        points: [
          "RAG บน Supabase + pgvector",
          "Tool-use card ในแชทเลย",
          "Edge runtime, EN/TH สองภาษา",
        ],
      },
      {
        k: "DASHBOARDS",
        points: [
          "Command Center สำหรับ VerdeX Farm",
          "ข้อมูล sensor + ธุรกิจ realtime",
          "RLS ทุก table, gate ตามผู้ใช้",
        ],
      },
      {
        k: "LINE OA",
        points: [
          "Rich Menu + Flex Messages + LIFF",
          "Weekly Pulse Reports จาก Claude",
          "Morning Report 07:00 รายวัน",
        ],
      },
    ],
    process_kicker: "[02] กระบวนการ",
    process: [
      {
        n: "01",
        t: "ค้นหา",
        d: "ปรึกษาฟรี 15 นาที. กรอกแบบฟอร์ม business / customers / FAQs / flow. หา constraint และวันส่งงานให้เจอ.",
      },
      {
        n: "02",
        t: "ออกแบบ",
        d: "Flow diagram + Rich Menu wireframe. อนุมัติเป็นลายลักษณ์อักษรก่อนเริ่มเขียน code. ไม่มี scope drift, ไม่มี surprise.",
      },
      {
        n: "03",
        t: "สร้าง & ทดสอบ",
        d: "Slice ที่ใช้งานได้บน staging ตามกรอบเวลาแพ็คเกจ. ข้อมูลจริง, โมเดลจริง, LINE OA จริง — กดปุ่มเดียวกับลูกค้า.",
      },
      {
        n: "04",
        t: "ส่งมอบ",
        d: "Deploy production. Source code + ENV doc + วิดีโอภาษาไทย + warranty. กุญแจเป็นของคุณตั้งแต่วันแรก.",
      },
    ],
    chat_kicker: "[03] คุยกับผม",
    chat_title: "ถาม PORTFOLIO ได้",
    chat_help: "ลองเริ่มจาก ↓",
    pdpa: "แชทนี้อาจบันทึกข้อความเพื่อปรับปรุงบริการ ข้อมูลจะไม่ถูกแบ่งปันกับบุคคลที่สาม",
    pdpa_accept: "เข้าใจแล้ว",
    placeholder: "คุณต้องการให้สร้างอะไร? เล่าเกี่ยวกับโปรเจคของคุณ...",
    send: "ส่ง",
    cap: "session :: สูงสุด 20 ข้อความ",
    cap_reached: "ถึงขีดจำกัดแล้ว — ติดต่อทาง LINE หรืออีเมล",
    suggest: [
      "เล่าเคส VerdeX Farm ให้ฟังหน่อย",
      "กัน hallucination ยังไง?",
      "chatbot ราคาเท่าไหร่?",
      "พ.ค. ว่างไหม?",
    ],
    contact_label: "ติดต่อ",
    contact: [
      { k: "LINE", href: "https://line.me/ti/p/EeqOwz9udS" },
      { k: "EMAIL", href: "mailto:prempaweet20@gmail.com" },
      { k: "LINKEDIN", href: "https://www.linkedin.com/in/prempaweedevth" },
      { k: "GITHUB", href: "https://github.com/premkung87-star" },
    ],
    footer_links: [
      { k: "VERDEX", href: "/case-studies/verdex" },
      { k: "PORTFOLIO META", href: "/case-studies/this-portfolio" },
      { k: "FALLBACK", href: "/fallback" },
      { k: "STATUS", href: "/status" },
    ],
    philosophy_kicker: "[02c] หลักการทำงาน",
    philosophy_quote:
      "สร้างรากฐานให้แข็งแกร่งที่สุด ลดจุดอ่อนก่อนที่จะเพิ่มจุดแข็ง",
    philosophy_attribution: "Prempawee · One Person Business",
    feedback_link: "ส่งข้อเสนอแนะ",
    feedback_kicker: "[ข้อเสนอแนะ]",
    feedback_type_label: "ประเภท",
    feedback_types: {
      bug: "บัก",
      suggestion: "ข้อเสนอแนะ",
      thanks: "ขอบคุณ",
      other: "อื่น ๆ",
    },
    feedback_body_label: "ข้อความ",
    feedback_body_placeholder: "อยากบอกอะไรกับเราไหม?",
    feedback_email_label: "อีเมล",
    feedback_email_help: "(ไม่บังคับ — ถ้าอยากให้ติดต่อกลับ)",
    feedback_email_placeholder: "you@example.com",
    feedback_consent:
      "การส่งข้อเสนอแนะเท่ากับยินยอมให้เก็บข้อความและอีเมล (ถ้ามี) ไม่มีการแชร์ข้อมูลกับบุคคลที่สาม",
    feedback_submit: "ส่ง",
    feedback_submitting: "กำลังส่ง...",
    feedback_thanks: "ขอบคุณ บันทึกข้อเสนอแนะของคุณแล้ว",
    feedback_close: "ปิด",
    feedback_error:
      "ส่งไม่สำเร็จ กรุณาลองใหม่หรือส่งอีเมลโดยตรง",
    feedback_error_validation: "กรุณากรอกแบบฟอร์มให้ถูกต้อง",
    feedback_error_rate_limited:
      "ส่งบ่อยเกินไป รอ 1 ชั่วโมงแล้วลองใหม่",
    welcome:
      "ยินดีต้อนรับ ผมคือ AI portfolio ของ Prempawee. เขาเป็น Solo AI Developer อยู่เชียงใหม่ ส่งมอบระบบ production ให้ธุรกิจไทย — LINE chatbot, admin dashboard, IoT, AI agent. ทั้งหมดใช้ Claude, deploy แล้ว, ใช้งานจริงอยู่",
  },
} as const;
