import type { Metadata, Viewport } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://prempawee.com";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0a0a0a",
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "PREMPAWEE // AI — LINE OA Chatbot Developer",
    template: "%s | PREMPAWEE // AI",
  },
  description:
    "I build intelligent LINE OA Chatbots for Thai businesses. AI-powered, smarter than keywords. Talk to my portfolio to see what I can build for you.",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "PREMPAWEE // AI — LINE OA Chatbot Developer",
    description:
      "I build intelligent LINE OA Chatbots for Thai businesses. Talk to my portfolio AI.",
    type: "website",
    url: siteUrl,
    siteName: "PREMPAWEE // AI",
    locale: "en_US",
    // OG image is generated by src/app/opengraph-image.tsx via next/og file convention.
  },
  twitter: {
    card: "summary_large_image",
    title: "PREMPAWEE // AI — LINE OA Chatbot Developer",
    description:
      "I build intelligent LINE OA Chatbots for Thai businesses. Talk to my portfolio AI.",
    // Twitter image is generated by src/app/twitter-image.tsx via next/og file convention.
  },
  robots: {
    index: true,
    follow: true,
  },
};

// JSON-LD structured data
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: "PREMPAWEE // AI",
  description:
    "Intelligent LINE OA Chatbot development for Thai businesses. AI-powered, smarter than keywords.",
  url: siteUrl,
  serviceType: "LINE OA Chatbot Development",
  areaServed: {
    "@type": "Country",
    name: "Thailand",
  },
  provider: {
    "@type": "Person",
    name: "Prempawee",
    url: siteUrl,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mono.variable} h-full`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-[#0a0a0a] text-[#e0e0e0] font-mono antialiased">
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
