import type { Metadata, Viewport } from "next";
import { EB_Garamond, JetBrains_Mono } from "next/font/google";
import { headers } from "next/headers";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { SITE_URL } from "@/lib/site-url";
import { PACKAGES, CONTACT } from "@/lib/portfolio-data";
import "./globals.css";

const mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const renaissance = EB_Garamond({
  variable: "--font-renaissance",
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  display: "swap",
});

const siteUrl = SITE_URL;

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
    { media: "(prefers-color-scheme: light)", color: "#0a0a0a" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "PREMPAWEE // AI — Solo AI Developer / Chiang Mai",
    template: "%s | PREMPAWEE // AI",
  },
  description:
    "Solo AI Developer in Chiang Mai shipping production systems for Thai businesses — LINE chatbots, admin dashboards, IoT platforms, AI agents. Claude-powered. Talk to my portfolio.",
  keywords: [
    "Solo AI Developer",
    "AI Developer Thailand",
    "LINE OA Chatbot",
    "LINE Messaging API",
    "Claude AI",
    "Claude-powered applications",
    "production systems",
    "full-stack AI developer",
    "Thai Chatbot",
    "Chiang Mai Developer",
    "Next.js Developer",
    "Supabase",
    "Supabase developer",
  ],
  alternates: {
    canonical: "/",
    languages: {
      en: siteUrl,
      th: `${siteUrl}/?lang=th`,
      "x-default": siteUrl,
    },
  },
  openGraph: {
    title: "PREMPAWEE // AI — Solo AI Developer / Chiang Mai",
    description:
      "Solo AI Developer based in Chiang Mai shipping production systems for Thai businesses — LINE chatbots, dashboards, IoT, AI agents. Claude-powered. Talk to my portfolio.",
    type: "website",
    url: siteUrl,
    siteName: "PREMPAWEE // AI",
    locale: "en_US",
    alternateLocale: ["th_TH"],
    // OG image is generated by src/app/opengraph-image.tsx via next/og file convention.
  },
  twitter: {
    card: "summary_large_image",
    title: "PREMPAWEE // AI — Solo AI Developer / Chiang Mai",
    description:
      "Solo AI Developer in Chiang Mai. Ships production systems — chatbots, dashboards, IoT, AI agents. Claude-powered.",
    // Twitter image is generated by src/app/twitter-image.tsx via next/og file convention.
  },
  robots: {
    index: true,
    follow: true,
  },
  authors: [{ name: "Prempawee", url: siteUrl }],
  creator: "Prempawee",
  publisher: "Prempawee",
};

// JSON-LD structured data — three linked schemas via @graph for Google
// Rich Results compatibility (Service, Person, Offers, FAQ, WebSite).
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteUrl}#website`,
      url: siteUrl,
      name: "PREMPAWEE // AI",
      description:
        "Portfolio of Prempawee — Solo AI Developer shipping production systems for Thai businesses.",
      publisher: { "@id": `${siteUrl}#person` },
      inLanguage: ["en", "th"],
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${siteUrl}/?q={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "Person",
      "@id": `${siteUrl}#person`,
      name: "Prempawee",
      alternateName: "Prempawee Thabburee",
      url: siteUrl,
      email: CONTACT.email,
      image: `${siteUrl}/opengraph-image`,
      jobTitle: "Solo AI Developer",
      knowsAbout: [
        "LINE Messaging API",
        "Claude AI",
        "Anthropic AI SDK",
        "Next.js",
        "Supabase",
        "TypeScript",
        "Cloudflare Workers",
        "AI Agent Development",
        "Full-stack Web Development",
        "Production Systems",
      ],
      knowsLanguage: ["en", "th"],
      address: {
        "@type": "PostalAddress",
        addressLocality: "Chiang Mai",
        addressRegion: "Chiang Mai",
        addressCountry: "TH",
      },
      sameAs: [CONTACT.linkedin],
    },
    {
      "@type": "ProfessionalService",
      "@id": `${siteUrl}#service`,
      name: "PREMPAWEE // AI",
      url: siteUrl,
      description:
        "Production AI systems for Thai businesses — LINE chatbots, admin dashboards, IoT platforms, AI agents. Claude-powered.",
      image: `${siteUrl}/opengraph-image`,
      serviceType: "AI Development",
      priceRange: "฿5,000 – ฿45,000",
      areaServed: {
        "@type": "Country",
        name: "Thailand",
      },
      provider: { "@id": `${siteUrl}#person` },
      address: {
        "@type": "PostalAddress",
        addressLocality: "Chiang Mai",
        addressCountry: "TH",
      },
      contactPoint: [
        {
          "@type": "ContactPoint",
          contactType: "customer support",
          email: CONTACT.email,
          availableLanguage: ["English", "Thai"],
        },
      ],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "LINE OA Chatbot Packages",
        itemListElement: PACKAGES.map((pkg, i) => ({
          "@type": "Offer",
          position: i + 1,
          name: pkg.name,
          description: `${pkg.desc} — ${pkg.delivery} delivery`,
          price: pkg.price.replace(/[^0-9]/g, ""),
          priceCurrency: "THB",
          availability: "https://schema.org/InStock",
          itemOffered: {
            "@type": "Service",
            name: pkg.name,
            description: pkg.features.join(" · "),
          },
        })),
      },
    },
    {
      "@type": "FAQPage",
      "@id": `${siteUrl}#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "What makes Prempawee's chatbots different from other chatbot services?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Prempawee's chatbots use Claude AI for natural Thai-language understanding rather than keyword matching. Built on Vercel Edge Network with Supabase Postgres for the RAG knowledge base. Backed by a Mass Communication degree from Chiang Mai University — both the technical side and the communication side are handled.",
          },
        },
        {
          "@type": "Question",
          name: "How many projects has Prempawee completed?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "3 major projects: VerdeX Farm (4 components — landing, blog, command center, LINE bot with 12 iterations across 6 major systems), NWL CLUB (2 production sites — Work Tracker + Community), and this AI-powered portfolio itself.",
          },
        },
        {
          "@type": "Question",
          name: "What is the pricing?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Three packages: LINE OA Starter at ฿5,000 (5-day delivery, rich menu + auto-reply), Smart Chatbot Pro at ฿18,000 (14-day delivery, Claude AI Thai NLU + CRM), Enterprise AI at ฿45,000 (30-day delivery, booking/payments/loyalty).",
          },
        },
        {
          "@type": "Question",
          name: "Where is Prempawee based?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Chiang Mai, Thailand. Serves Thai businesses nationwide via LINE OA, which is Thailand's dominant messaging platform.",
          },
        },
      ],
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // nonce is set by src/proxy.ts per-request; undefined in dev (CSP off).
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  return (
    <html lang="en" className={`${mono.variable} ${renaissance.variable} h-full`}>
      <head>
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
          }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-[#0a0a0a] text-[#e0e0e0] font-mono antialiased">
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
