import type { Metadata, Viewport } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { SITE_URL } from "@/lib/site-url";
import { PACKAGES, CONTACT } from "@/lib/portfolio-data";
import "./globals.css";

const mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const siteUrl = SITE_URL;

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
    { media: "(prefers-color-scheme: light)", color: "#0a0a0a" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "PREMPAWEE // AI — LINE OA Chatbot Developer",
    template: "%s | PREMPAWEE // AI",
  },
  description:
    "LINE OA Chatbot developer for Thai businesses — Claude AI for natural Thai-language understanding, not keyword matching. Talk to my portfolio to see what I can build.",
  keywords: [
    "LINE OA Chatbot",
    "LINE Messaging API",
    "Claude AI",
    "Thai Chatbot",
    "Chiang Mai Developer",
    "Next.js Developer",
    "Supabase",
    "AI Developer Thailand",
  ],
  alternates: {
    canonical: "/",
    languages: {
      en: siteUrl,
      th: `${siteUrl}/?lang=th`,
      "x-default": siteUrl,
    },
  },
  openGraph: {
    title: "PREMPAWEE // AI — LINE OA Chatbot Developer",
    description:
      "LINE OA Chatbot developer for Thai businesses — Claude AI for natural Thai-language understanding. Talk to my portfolio.",
    type: "website",
    url: siteUrl,
    siteName: "PREMPAWEE // AI",
    locale: "en_US",
    alternateLocale: ["th_TH"],
    // OG image is generated by src/app/opengraph-image.tsx via next/og file convention.
  },
  twitter: {
    card: "summary_large_image",
    title: "PREMPAWEE // AI — LINE OA Chatbot Developer",
    description:
      "LINE OA Chatbot developer for Thai businesses — Claude AI for natural Thai NLU.",
    // Twitter image is generated by src/app/twitter-image.tsx via next/og file convention.
  },
  robots: {
    index: true,
    follow: true,
  },
  authors: [{ name: "Prempawee", url: siteUrl }],
  creator: "Prempawee",
  publisher: "Prempawee",
};

// JSON-LD structured data — three linked schemas via @graph for Google
// Rich Results compatibility (Service, Person, Offers, FAQ, WebSite).
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteUrl}#website`,
      url: siteUrl,
      name: "PREMPAWEE // AI",
      description:
        "Portfolio of Prempawee — LINE OA Chatbot developer for Thai businesses.",
      publisher: { "@id": `${siteUrl}#person` },
      inLanguage: ["en", "th"],
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${siteUrl}/?q={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "Person",
      "@id": `${siteUrl}#person`,
      name: "Prempawee",
      alternateName: "Prempawee Thabburee",
      url: siteUrl,
      email: CONTACT.email,
      image: `${siteUrl}/opengraph-image`,
      jobTitle: "LINE OA Chatbot Developer",
      knowsAbout: [
        "LINE Messaging API",
        "Claude AI",
        "Anthropic AI SDK",
        "Next.js",
        "Supabase",
        "TypeScript",
        "Cloudflare Workers",
        "AI Agent Development",
      ],
      knowsLanguage: ["en", "th"],
      address: {
        "@type": "PostalAddress",
        addressLocality: "Chiang Mai",
        addressRegion: "Chiang Mai",
        addressCountry: "TH",
      },
      sameAs: [CONTACT.linkedin],
    },
    {
      "@type": "ProfessionalService",
      "@id": `${siteUrl}#service`,
      name: "PREMPAWEE // AI",
      url: siteUrl,
      description:
        "LINE OA Chatbot development for Thai businesses — Claude AI for natural Thai-language understanding.",
      image: `${siteUrl}/opengraph-image`,
      serviceType: "LINE OA Chatbot Development",
      priceRange: "฿5,000 – ฿45,000",
      areaServed: {
        "@type": "Country",
        name: "Thailand",
      },
      provider: { "@id": `${siteUrl}#person` },
      address: {
        "@type": "PostalAddress",
        addressLocality: "Chiang Mai",
        addressCountry: "TH",
      },
      contactPoint: [
        {
          "@type": "ContactPoint",
          contactType: "customer support",
          email: CONTACT.email,
          availableLanguage: ["English", "Thai"],
        },
      ],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "LINE OA Chatbot Packages",
        itemListElement: PACKAGES.map((pkg, i) => ({
          "@type": "Offer",
          position: i + 1,
          name: pkg.name,
          description: `${pkg.desc} — ${pkg.delivery} delivery`,
          price: pkg.price.replace(/[^0-9]/g, ""),
          priceCurrency: "THB",
          availability: "https://schema.org/InStock",
          itemOffered: {
            "@type": "Service",
            name: pkg.name,
            description: pkg.features.join(" · "),
          },
        })),
      },
    },
    {
      "@type": "FAQPage",
      "@id": `${siteUrl}#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "What makes Prempawee's chatbots different from other chatbot services?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Prempawee's chatbots use Claude AI for natural Thai-language understanding rather than keyword matching. Built on production-grade infrastructure (Vercel 99.99% uptime, Supabase). Backed by a Mass Communication degree from Chiang Mai University — both the technical side and the communication side are handled.",
          },
        },
        {
          "@type": "Question",
          name: "How many projects has Prempawee completed?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "3 major projects: VerdeX Farm (4 components — landing, blog, command center, LINE bot with 12 iterations across 6 major systems), NWL CLUB (2 production sites — Work Tracker + Community), and this AI-powered portfolio itself.",
          },
        },
        {
          "@type": "Question",
          name: "What is the pricing?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Three packages: LINE OA Starter at ฿5,000 (5-day delivery, rich menu + auto-reply), Smart Chatbot Pro at ฿18,000 (14-day delivery, Claude AI Thai NLU + CRM), Enterprise AI at ฿45,000 (30-day delivery, booking/payments/loyalty).",
          },
        },
        {
          "@type": "Question",
          name: "Where is Prempawee based?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Chiang Mai, Thailand. Serves Thai businesses nationwide via LINE OA, which is Thailand's dominant messaging platform.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mono.variable} h-full`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-[#0a0a0a] text-[#e0e0e0] font-mono antialiased">
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
